### ISSUE TITLE
Crypto4Good #3: Blockchain for Financial Inclusion -  Including the Unincluded

### ISSUE THREAD

**Issue by mirelamus** [cesalazar/berlinblockchainweek#108]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Crypto4Good #3: Blockchain for Financial Inclusion -  Including the Unincluded

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: When it comes to financial inclusion, major challenges include poor financial and digital literacy as well as the lack of identification documents. However, DLT can also be leveraged to restructure control over personal data, such as identification and empower users to participate in financial markets. 

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Crypto4Good #3: Blockchain for Financial Inclusion -  Including the Unincluded

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
DSTOQ, GIZ Blockchain Lab, and Jolocom are partnering for the 3rd Crypto4Good panel discussion, featuring experts from both the tech world and the international development sector. This event will aim to define practical answers to a global issue, financial exclusion, and uncover how DLT (distributed ledger technology) could bring positive change. 
  -
Around two billion people worldwide do not have access to the financial services that meet their needs. Whether as individuals or small and medium enterprises (SMEs), many struggle to obtain sufficient financing to lift them off poverty, establish a sustained source of income or gain the opportunity to obtain shares and invest in assets. DLT could alleviate some of these challenges thanks to its decentralized and tamper-proof infrastructure, with intermediary-free remittances, credit-history for micro-loans or innovative and accessible tokenized-assets investments. 
  -
Though the features of blockchain-based solutions might sound very promising, there are several issues to be tackled. When it comes to financial inclusion, major challenges include poor financial and digital literacy as well as the lack of identification documents. However, DLT can also be leveraged to restructure control over personal data, such as identification and empower users to participate in financial markets. 
  -
    This event will be the occasion to discuss both the opportunities the technology offers and its possible challenges while assessing the conditions in which these solutions could be implemented and what might hinder their widespread adoption. 

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-10
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-10

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:00'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/DSTOQ-Exchange-Without-Borders/events/253975157/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Impact Hub

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Friedrichstraße 246, 10969 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Craig Mc Gregor

    # Can be left empty.
    title: Co-Founder

    # Can be left empty.
    company: DSTOQ

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://dstoq.com

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: 

    # The full URL, including http(s)://. Can be left empty.
    website: https://dstoq.com

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Investment analyst, trader, and economic strategist; managed a ~$600m portfolio of 30+ companies. Involved in crypto since 2013.
  -
    name: Craig Mc Gregor
    title: Co-founder
    company: DSTOQ
    companyURL: https://dstoq.com
    twitter: 
    website: 
    bio: Investment analyst, trader, and economic strategist; managed a ~$600m portfolio of 30+ companies. Involved in crypto since 2013.
  -
    name:  Anthony Barker
    title: CTO
    company: Tempo
    companyURL: 
    twitter:
    website: 
    bio: 
  -
    name:  Kai Wagner 
    title: Business Development
    company: Jolocom
    companyURL: 
    twitter:
    website: 
    bio: 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thanks for submitting this event. However, this can't be published in the current form because it is missing few fields (title, name, description...).

Please complete the missing fields by editing your comment, and leave a new comment below this one so I can get notified.

**Comment by mirelamus** [comment]
Added  (title, name, description...)
