### ISSUE TITLE
Blockchain for Real Estate

### ISSUE THREAD

**Issue by jedelsky** [cesalazar/berlinblockchainweek#125]
---
####################
####################
# This file is a template to create new events. In order to use it, duplicate
# the whole folder (/template) as a new folder (I.E. /my-event-name) inside of
# the /events folder, using for the folder name _only_:
# - lowercase letters
# - hyphens/dashes (-) instead of spaces
# - alphanumeric characters ('a' to 'z', '0' to '9')
# and edit the README.md file inside that new folder just created.
#
# The name of the folder will be used on the URL. Example:
# https://blockchainweek.berlin/my-event-name
#
# _Don't_ rename the new file (README.md), only edit its content.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: FIBREE - Blockchain for Real Estate

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: This meetup series is hosted by FIBREE and is either for
  real-estate-people who are interested in how to use blockchain technology or
  for blockchain enthusiasts who like to understand more about real estate -
  both with the aim to innovate the real estate industry.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Blockchain for Real Estate

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    'This meetup is a collaboration between three organisations:'
  -
    list:
    - '[SIBB e.V.](https://www.sibb.de) / Adam Formanek'
    - '[Berlin Partners](https://www.berlin-partner.de) / Christian Ruhle'
    - '[FIBREE](https://fibree.org/) / Achim Jedelsky'
  -
    With this event we aim to bring our specific communities together and
      create dynamic innovation within the context of blockchain and real
      estate, but also between Germany Berlin, Brandenburg and Poland.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-06
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-056

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '19:00'
time: '20:00'
# Time when the event ends. Can be left empty.
endTime: '21:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/de-DE/Blockchain-for-Real-Estate/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Immobilienscout24

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Andreasstraße 10, 10243 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    name: Michał Załęcki
    title: 
    company: Tooploox 
    companyURL: https://www.tooploox.com/
    twitter: 
    website: 
    bio: 
  -
    name: Lucas Hänke
    title: 
    company: inno2grid GmbH
    companyURL: https://inno2grid.com/
    twitter: 
    website: 
    bio: 
  -
    name: Beth McCarthy
    title: 
    company: Bee Token
    companyURL: https://www.beetoken.com/
    twitter: 
    website: 
    bio: 
  -
    name: Katrie Lowe
    title: 
    company: Fair Housing
    companyURL: 
    twitter: breitwoman
    website: 
    bio: 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thanks for submitting this event. However, the submission is missing fields. Please read the instructions, fill the fields accordingly, and resubmit. Otherwise this can't be published.

**Comment by cesalazar** [comment]
Also, typos.

**Comment by cesalazar** [comment]
* _Don't_ remove any text before the colons at the beginning of each line:
https://github.com/cesalazar/berlinblockchainweek/blame/master/events/template/README.md#L17

The content you submitted is missing some fields (any word before the colons), is using underscore (`_`) for indentation (Why!?), and has text randomly applied on the body. Again, _please_, **read** the instructions.

Example:
    - Correct: `title: FIBREE - Blockchain for Real Estate`
    - Incorrect: `## FIBREE - Blockchain for Real Estate`

Here's the template, I suggest you copy it completely and fill in the fields:
https://raw.githubusercontent.com/cesalazar/berlinblockchainweek/master/events/template/README.md

**Comment by jedelsky** [comment]
Is it now okay?

**Comment by cesalazar** [comment]
No. I guess the instructions aren't clear enough :confused:, but thanks for trying.

**Comment by cesalazar** [comment]
No prob. Updated the event.
