### ISSUE TITLE
Token Wirtschaft 

### ISSUE THREAD

**Issue by megan-doyle** [cesalazar/berlinblockchainweek#128]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Token Wirtschaft

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: We invite you to join us at the end of Berlin Blockchain Week for an epic afternoon  of deep diving into the dynamic world of token engineering and protocols.  Our first Token Wirtschaft will offer intimate, thought-provoking sessions with world-recognised speakers, music and a range of hands-on, relaxed workshops led by industry experts in token engineering and economics.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Token Wirtschaft 

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    We invite you to join us at the end of Berlin Blockchain Week for an epic afternoon  of deep diving 
     into the dynamic world of token engineering and protocols.  Our first Token Wirtschaft will offer 
     intimate, thought-provoking sessions with world-recognised speakers, music and a range of hands- 
     on, relaxed workshops led by industry experts in token engineering and economic
  -
    The Token Foundry, Linum Labs and The Energy Web Foundation are proud to invite you to an 
     exciting day at The Castle in Kreusberg, aka the "Sixtus Villa", a private residence in Kreuzberg and 
     also the portal to the Schultheiss brewery.
  -
    This event is a great opportunity to connect with the leading minds and engineers in the blockchain 
     community, and engage with others who want to talk about the potential of tokens through a 
     sophisticated lens. 

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-10
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-10

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '12:00'
# Time when the event ends. Can be left empty.
endTime: '19:30'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.tokenwirtschaft.com/attend

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: The Castle

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Sixtus Villa, Kreuzberg, 10969 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: workshop 

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:

  -
    name: Angela Kreitenweis
    bio: Angela is an initiator, networker and host for Token Engineering Berlin.
  -
    name: Garrett MacDonald
    bio: Garret is the Director of Cryptoeconomics at The Energy Web Foundation.
 -
    name: Trent McConaghy
    bio: Trent is the Founder of Ocean Protocol and BigchainDB.
  -
    name: Dimitri de Jonghe
    bio: Dimitri is Head of Research (Ocean Protocol) at BigchainDB & Co-Founder at Ocean Protocol.
 -
    name: Paul Kohlhaas
    bio: Blockchain Architect, Entrepreneur and Founder of Linum Labs and Molecule. 
 -
    name: Arthur Röing Baer
    bio: Arthur is the Creative Marketing Director at FOAM.
  -
    name: Anish Mohammed
    bio: Technologist with multidisciplinary background who is passionate about technology.
 -
    name: Julia Morrongiello
    bio: Associate at Point Nine Capital, covering all things crypto/blockchain and marketplaces.
 -
    name: Ryan John King
    bio: Ryan works between Real Estate, Architecture, Political Economy and Digital Technology and is 
    the co-founder of the spatial protocol FOAM.
  -
    name: Min Teo
    bio: Min Teo drives Strategic Initiatives & Investments at ConsenSys.
 -
    name: Lasse Clausen
    bio: Tech founder turned token angel investor at 1kx. 
 -
    name: Clément Lesaege
    bio: Computer Scientist and CTO working on the Kleros (a Decentralized Arbitration Court project).
 -

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thanks for submitting this event. The address doesn't resolve on Google Maps, hence the address link is invalid. Please check and make the correction.
