### ISSUE TITLE
Forking the repo for Prague Blockchain Week

### ISSUE THREAD

**Issue by JosefJ** [cesalazar/berlinblockchainweek#131]
Hi, I couldn't find your contact, neither licencing file so I'm opening an issue (hope you don't mind). 

Would it be fine to fork the repo for a similar initiative - Prague Blockchain Week?

Is there any requirement from your side? 
My email for any communication: josef@polynom.com 

Thanks,
JJ

**Comment by cesalazar** [comment]
Hey, no worries, fork away and do as you please! The license is MIT. I'll add it.

**Comment by cesalazar** [comment]
Closed on 994f2e835691cc924ca57fd8d6cdee4e989f6fc1. Feel free to reach if you need help.

**Comment by JosefJ** [comment]
Thanks for that and also for the work done on the code and the contribution process itself! Love it :)
