### ISSUE TITLE
Identity on Blockchain. ERC725 Alliance Demo and Meetup

### ISSUE THREAD

**Issue by andrewhyde** [cesalazar/berlinblockchainweek#134]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Identity on Blockchain. ERC725 Alliance Demo and Meetup

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: We are excited to launch the ERC725 Alliance to celebrate Berlin Blockchain Week! What is ERC 725? ERC 725 is a proposed standard for blockchain-based identity authored by Fabian Vogelsteller, creator of ERC 20 and Web3.js. ERC 725 describes proxy smart contracts that can be controlled by multiple keys and other smart contracts. ERC 735 is an associated standard to add and remove claims to an ERC 725 identity smart contract. These identity smart contracts can describe humans, groups, objects, and machines. ERC 725 lives on the Ethereum blockchain.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Identity on Blockchain. ERC725 Alliance Demo and Meetup

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    We are excited to launch the ERC725 Alliance to celebrate Berlin Blockchain Week! 
  -
    What is ERC 725?
  -
    ERC 725 is a proposed standard for blockchain-based identity authored by Fabian Vogelsteller, creator of ERC 20 and Web3.js. ERC 725 describes proxy smart contracts that can be controlled by multiple keys and other smart contracts. ERC 735 is an associated standard to add and remove claims to an ERC 725 identity smart contract. These identity smart contracts can describe humans, groups, objects, and machines. ERC 725 lives on the Ethereum blockchain.
  -
    Join us for a demo and discussion for the author and projects building on ERC 725! 

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-06
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-06

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '22:30'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/identity-on-blockchain-erc725-alliance-demo-and-meetup-tickets-49367472439

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Base58 

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Chausseestraße 86, 10115 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Carlos E. Salazar

    # Can be left empty.
    title: ERC 725 Author

    # Can be left empty.
    company: Least Authority

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://leastauthority.com

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: cesalazar

    # The full URL, including http(s)://. Can be left empty.
    website: https://cesalazar.com

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Here goes Carlos' description. Amet corporis laudantium obcaecati
      perferendis reiciendis rem perferendis. Magni qui reiciendis explicabo.
  -
    name: Stan James
    title: Lead Developer
    company: Origin Protocol
    companyURL: https://originprotocol.com
    twitter: wanderingstan
    website: http://wanderingstan.com/
    bio: Stan is the lead developer at Origin Protocol.

  -
    name: Josh Fraser
    title: Founder
    company: Origin Protocol
    companyURL: https://originprotocol.com
    twitter: joshfraser
    website: http://originprotocol.com
    bio: Co-founder at Origin Protocol: building the sharing economy without intermediaries.

  -
    name: Fabian Vogelsteller
    title: Founder
    company: LUKSO
    companyURL: https://www.lukso.io/
    twitter: feindura
    website: http://frozeman.de/blog/
    bio: Ethereum developer, creator of the Ethereum-Wallet and the Mist browser, author of a Meteor.js book and creator of the feindura - flat file CMS.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thanks for adding this event!
