### ISSUE TITLE
After Work Session Curated by Volareo

### ISSUE THREAD

**Issue by thevenueberlin** [cesalazar/berlinblockchainweek#137]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: After Work Session Curated by Volareo

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: The Venue Berlin (a hub for all things pertaining to the future of audio and music) is hosting an After Work Session curated by the world’s first open source music streaming smart speaker Volareo.

Volareo is coming all the way from Rotterdam to discuss the newest technologies currently transforming the music industry, the benefits of blockchain for musicians, blockchain-streaming platforms & their advantages, as well as kickstarting your career as a music maker with blockchain.

Free beer and pizza!

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: After Work Session Curated by Volareo

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
   The Venue Berlin (a hub for all things pertaining to the future of audio and music) is hosting an After Work Session curated by the world’s first open source music streaming smart speaker Volareo.
  -
  Volareo is coming all the way from Rotterdam to discuss the newest technologies currently transforming the music industry, the benefits of blockchain for musicians, blockchain-streaming platforms & their advantages, as well as kickstarting your career as a music maker with blockchain.
  -

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-08-30
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '20:30'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.facebook.com/events/291718198053225/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: The Venue Berlin

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Mehringdamm 33, 10961 Berlin

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.

    # Can be left empty.

    # Can be left empty.

    # The full URL, including http(s)://. Can be left empty.

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.

    # The full URL, including http(s)://. Can be left empty.

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thank you for submitting this event. However, events outside of the dates of Berlin Blockchain Week (5-11 Sept) can't be included on this website. You're welcome to modify the dates to fit within the scope of BERBlockWeek.

**Comment by thevenueberlin** [comment]
Hi Carlos,

Thank you. Is there a social media channel with pre-events where this could be shared?


Best,
Amelie

Amélie Gagné

THE VENUE BERLIN
Mehringdamm 33
10961 Berlin

Mobile: +49 (0) 157 58985002
Mail: amelie@thevenueberlin.com<mailto:amelie@thevenueberlin.com>

Follow us on Facebook: www.facebook.com/thevenueberlin/<http://www.facebook.com/thevenueberlin/>

**Comment by cesalazar** [comment]
> Is there a social media channel with pre-events where this could be shared?

Not that I'm aware of, as I'm only involved with the website. Maybe reach out [@BERBlockWeek](https://twitter.com/BERBlockWeek) and ask.

**Comment by thevenueberlin** [comment]
Awesome, thanks a bunch!

Amelie

Amélie Gagné

THE VENUE BERLIN
Mehringdamm 33
10961 Berlin

Mobile: +49 (0) 157 58985002
Mail: amelie@thevenueberlin.com<mailto:amelie@thevenueberlin.com>

Follow us on Facebook: www.facebook.com/thevenueberlin/<http://www.facebook.com/thevenueberlin/>
