### ISSUE TITLE
Pandora Boxchain Meetup || Blockchain Week Berlin 2018

### ISSUE THREAD

**Issue by dany2aa** [cesalazar/berlinblockchainweek#142]
---
title: Pandora Boxchain Meetup || Blockchain Week Berlin 2018
Description: Pandora Boxchain welcomes all blockchain and AI enthusiasts to its second meetup in Berlin!
  Join us for pizza & beer right after the Zero Knowledge Summit at Mindspace.
  We will kick off with the presentation by Andrey Sobol on the topic ‘Randomness in POS blockchains’. 

name: Pandora Boxchain Meetup || Blockchain Week Berlin 2018

synopsis:
  -
    Pandora Boxchain welcomes all blockchain and AI enthusiasts to its second meetup in Berlin!
      Join us for pizza & beer right after the Zero Knowledge Summit at Mindspace.
  -
    We will kick off with the presentation by Andrey Sobol on the topic
      ‘Randomness in POS blockchains’.

date: 2018-09-05
endDate: 2018-09-05

time: '19:00'
endTime: '21:00'

https://www.meetup.com/pandoraboxchain-berlin-meetup/events/254212923/

price: 

venue: Mindspace - Coworking Space in Berlin

address: Krausenstraße 9-10, 10117 Berlin, Germany

category: event

speakers:
  -
    name: Andrey Sobol

    title: Co-founder

    company: Pandora Boxchain

    companyURL: https://pandoraboxchain.ai/

    twitter: andrENsobol

    website:

    bio: Andrey Sobol is a co-founder of Pandora Boxchain, CTO of Satoshi Fund,
      consensus protocol researcher and author of Hyperion consensus protocol.
      Andrey is an experienced software developer, focused on distributed technologies,
      artificial intelligence and cryptography. He also holds expertise in Game Theory,
      Austrian Theory on Business Cycle, and Decentralization Law.

---

<Event-Content/>

**Comment by dany2aa** [comment]
@cesalazar Carlosб please update the event.
I've edited info in the 1st comment.

**Comment by cesalazar** [comment]
Please don't use closed issues to request changes. Open a new one instead, using the current content of the page. Here's the current content: https://raw.githubusercontent.com/cesalazar/berlinblockchainweek/master/events/add-pandora-boxchain-meetup/README.md
