### ISSUE TITLE
Update event location: Decoding Token Economics

### ISSUE THREAD

**Issue by pauldups** [cesalazar/berlinblockchainweek#147]
---
###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: 'Decoding Token Economics: A Token Engineering and Token Economy Design
  Workshop'

# Description for this event. This will be rendered as a <meta> tag in the HTML, 
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Join us for a comprehensive workshop featuring the token experts
  of OST and Ocean Protocol sharing their knowledge on the best ways to design
  and engineer a token economy as well as optimal use cases for implementing a
  token economy.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: 'Decoding Token Economics: A Token Engineering and Token Economy Design
  Workshop'

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Join us for a comprehensive workshop featuring the token experts of OST
      and Ocean Protocol sharing their knowledge on the best ways to design and
      engineer a token economy as well as optimal use cases for implementing a
      token economy.
  -
    'We will cover a wide range of topics including:'
  -
    list:
    - How tokens can incentivize global collaboration
    - What types of businesses and environments provide the best climate for
        tokenization
    - Best practices and models for token engineering frameworks
    - How to align your business goals to design a token economy
   

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-06
# Leave this field empty if the event is held only during one day.
endDate: 2018-09-06

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '13:00'
endTime: '17:00'

# The URL where to acquire the tickets. Can be left empty.
tickets: https://www.meetup.com/de-DE/Token-Engineering/events/253174971/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: betahaus

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Köpenicker Str. 154 · Berlin

# The category of the event. Valid options:
# - conference
# - event
# - hackaton
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: workshop

 
#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    name: Dimitri De Jonghe 
    title: Head of Product and Research
    company: Ocean Protocol
    companyURL: https://oceanprotocol.com/
    twitter: 
    website: 
    bio: 
  -
    name: Trent McConaghy
    title: Founder
    company: Ocean Protocol
    companyURL: https://oceanprotocol.com/
    twitter: 
    website: 
    bio: 
  -
    name: Mohit Anand 
    title: Director of Blockchain Strategy Consultancy 
    company: OST
    companyURL: https://ost.com/
    twitter: 
    website: 
    bio: 
  -
    name: Benjamin Bollen
    title: Founder and Chief Blockchain Strategist
    company: OST 
    companyURL: https://ost.com/
    twitter: 
    website: 
    bio: 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Please use the [current content of the event](https://raw.githubusercontent.com/cesalazar/berlinblockchainweek/master/events/decoding-token-economics/README.md): copy everything, edit your issue with the updates, save, and leave a new comment so I get notified.

**Comment by pauldups** [comment]
---
###########
### SEO ###
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: 'Decoding Token Economics: A Token Engineering and Token Economy Design
  Workshop'

# Description for this event. This will be rendered as a <meta> tag in the HTML, 
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Join us for a comprehensive workshop featuring the token experts
  of OST and Ocean Protocol sharing their knowledge on the best ways to design
  and engineer a token economy as well as optimal use cases for implementing a
  token economy.


#####################
### EVENT DETAILS ###
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: 'Decoding Token Economics: A Token Engineering and Token Economy Design
  Workshop'

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Join us for a comprehensive workshop featuring the token experts of OST
      and Ocean Protocol sharing their knowledge on the best ways to design and
      engineer a token economy as well as optimal use cases for implementing a
      token economy.
  -
    'We will cover a wide range of topics including:'
  -
    list:
    - How tokens can incentivize global collaboration
    - What types of businesses and environments provide the best climate for
        tokenization
    - Best practices and models for token engineering frameworks
    - How to align your business goals to design a token economy
   

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-06
# Leave this field empty if the event is held only during one day.
endDate: 2018-09-06

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '13:00'
endTime: '17:00'

# The URL where to acquire the tickets. Can be left empty.
tickets: https://www.meetup.com/de-DE/Token-Engineering/events/253174971/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Ocean Protocol

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: betahaus, Köpenicker Str. 154 · Berlin

# The category of the event. Valid options:
# - conference
# - event
# - hackaton
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: workshop

 
#################
### SPEAKERS ####
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    name: Dimitri De Jonghe 
    title: Head of Product and Research
    company: Ocean Protocol
    companyURL: https://oceanprotocol.com/
    twitter: 
    website: 
    bio: 
  -
    name: Trent McConaghy
    title: Founder
    company: Ocean Protocol
    companyURL: https://oceanprotocol.com/
    twitter: 
    website: 
    bio: 
  -
    name: Mohit Anand 
    title: Director of Blockchain Strategy Consultancy 
    company: OST
    companyURL: https://ost.com/
    twitter: 
    website: 
    bio: 
  -
    name: Benjamin Bollen
    title: Founder and Chief Blockchain Strategist
    company: OST 
    companyURL: https://ost.com/
    twitter: 
    website: 
    bio: 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---


<Event-Content/>
