### ISSUE TITLE
DBF CONNECT MEETUP: Test Automation for Blockchain-based Applications

### ISSUE THREAD

**Issue by odurace** [cesalazar/berlinblockchainweek#157]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: DBF CONNECT MEETUP: Test Automation for Blockchain-based Applications

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Join us for an insightful review of strategies, tools, and techniques for testing smart-contract-based applications in a continuous integration / continuous delivery development environment. Digital Blockchain Foundation's Senior Developer Olivier Abdoun will reveal DBF Connect's 'ethest': testing framework, rationale, usage and implementation details - this event is open and free to attend!

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: DBF CONNECT MEETUP: Test Automation for Blockchain-based Applications

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Digital Blockchain Foundation's Senior Developer Olivier Abdoun will reveal DBF Connect's 'ethest': testing framework, rationale, usage and implementation details - this event is open and free to attend! 

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-11
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-11

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '19:30'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/test-automation-for-blockchain-based-applications-tickets-49644069749?aff=efbeventtix

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: CUBE GmbH Office

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Französische Strasse 24, 10117 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: panel

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Olivier Abdoun

    # Can be left empty.
    title: Senior Developer

    # Can be left empty.
    company: Digital Blockchain Foundation

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://dbfconnect.io/

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: 

    # The full URL, including http(s)://. Can be left empty.
    website: 

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Olivier is a software developer with 20+ years of experience working in FinTech sector for the past 10 years with the main focus on scaling out online services and automating operations.
  -
   
### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thanks for submitting this event. However, the synopsis is still the default template and the address (or venue?) seems wrong: Full Node is not located on that address. Please fix those problems by editing the issue and leave a comment below this one for me to be notified.

**Comment by odurace** [comment]
I updated the info.

**Comment by odurace** [comment]
Hi, is it possible to change the event category from panel to event? Thanks.
