### ISSUE TITLE
Add Fully Booked notice

### ISSUE THREAD

**Issue by mariapaulafn** [cesalazar/berlinblockchainweek#172]
Hi guys, I am getting flooded by last minute requests we cannot cater.
Can you add "FULLY BOOKED" to the title
and "This event has been fully booked and all community tickets allocated. No more passes will be given. Waitlist has been closed too. No spontaneous drop-bys please, restricted admission to hackathon participants."

**Comment by cesalazar** [comment]
Sorry, Berlin Blockchain Week started already, no updates nor new events will be added to the website (plus the template wasn't used on your issue).
