### ISSUE TITLE
Blockchain Startup Pitch meetup

### ISSUE THREAD

**Issue by JZhtIexXqS** [cesalazar/berlinblockchainweek#198]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Blockchain Startup Pitch meetup

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: The meetup is a great opportunity to share your project with the Blockchain community and learn what others are doing in the space. 

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Blockchain Startup Pitch meetup

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  
  -
    Rules are simple: each project will have a chance to do a max. 10 min.  presentation + short Q&A

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-09
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-09

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '19:00'
# Time when the event ends. Can be left empty.
endTime: '21:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/Blockchain-Startup-Pitch/events/254411133/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: rent24

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: POTSDAMER STRASSE 182, 10783 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  
  -
    name: Ania Bywanis
    company: Arteia
    companyURL: https://arteia.com/
  -
    name: Simon Szczepankowski
    company: Buddy
    companyURL: https://token.buddy.works/
  -
    name: Włodek Laskowski
    company: Cardiolyse 
    companyURL: https://cardiolyse.com/
  -
    name: Stephen Bartlett-Bragg
    company: East2
    companyURL: http://east2.global/
  -
    name: Volker Brendel
    company: KodakOne 
    companyURL: https://kodakone.com/
  -
    name: Mat Lagowski
    company: Usecrypt 
    companyURL: https://usecrypt.com/

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
The content of this issue is invalid.

Please **read** the instructions, and adjust the content accordingly.
Otherwise this won't be included on the website.

Hint: the synopsis cannot be left empty and the description cannot be that
long, the hypens and spaces can't be randomly removed...

**Comment by JZhtIexXqS** [comment]
Fixing it...
Thanks!

**Comment by JZhtIexXqS** [comment]
Fixed. Could you please take a look and add it to the events list?
