### ISSUE TITLE
Change the date for the new Blockchain week

### ISSUE THREAD

**Issue by bettabeta** [cesalazar/berlinblockchainweek#210]
Please update the date to the ones of the new Berlin Blockchain Week.
The new date are:
20th to 28th

Whereby: 
I think Metacartel wants to do something on the 20th.
21st to the 23rd of August is reserved for dAppcon
23rd at night to the Factory for till the 27th for ETHBerlin

**Comment by cesalazar** [comment]
Hey @zulfacar this repo is for the year 2018, and I won't be involved on Berlin Blockchain Week anymore, but anybody can fork and update for this year.

The DNS of the domain will have to point to the new website or GitHub Pages of the repo.

Cheers!

**Comment by bettabeta** [comment]
@cesalazar ahhh ok then I need to rethink how we do it..thanks for your fast response..#guasacaca for all
