### ISSUE TITLE
Remove template descriptions

### ISSUE THREAD

**Issue by HeyChristopher** [cesalazar/berlinblockchainweek#38]
Some events still have template descriptions which makes all the legit information on the website less credible.

![photo_2018-08-03_16-46-47](https://user-images.githubusercontent.com/32675161/43631052-1a314bbe-973d-11e8-9500-7b28b5208ced.jpg)
![photo_2018-08-03_16-46-56](https://user-images.githubusercontent.com/32675161/43631053-1a64fb30-973d-11e8-9bf4-51f1edc29424.jpg)

**Comment by cesalazar** [comment]
Fixed on 75136635c4cf91bf960505e62a2e3f3d2b20b1d4
