### ISSUE TITLE
Price is displayed wrong for Dezentral

### ISSUE THREAD

**Issue by HeyChristopher** [cesalazar/berlinblockchainweek#44]
in the readme the price is stated to be: 
"50-150"

however, on the website it displays "free" which is a bit misleading. 

Is there a problem on the readme or it just didn't update correctly?

**Comment by cesalazar** [comment]
The price should be either a number or empty. Because this is set as a range with a dash, the system thinks this is text and displays the word 'free'. I'll look into it.
