### ISSUE TITLE
Security Unconf by SecurETH

### ISSUE THREAD

**Issue by mariapaulafn** [cesalazar/berlinblockchainweek#45]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# Security Unconf
# Security Unconf by SecurETH
title: Security Unconf by SecurETH

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Gathering of the Ethereum Security Community. This initiative is organized by SecurETH in collaboration with other initiatives.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Security Unconf by SecurETH

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
 Gathering of the Ethereum Security Community. This initiative is organized by SecurETH in collaboration with other initiatives.
  -
Sign-ups and discussions [please suggest here.](https://ethereum-magicians.org/t/wiki-gathering-of-security-community/433) 
  -

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-06
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '8:00'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://eventbrite.com/my-event

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: FULL NODE

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Skalitzer Strasse 85-86, 10997 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category:  worshop

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Bryant Eisenbach

    # Can be left empty.
    title: SecurETH

    # Can be left empty.
    company: 

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://secureth.org/

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: fubuloubu

    # The full URL, including http(s)://. Can be left empty.
    website: 

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: 
  -

  -

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thanks!

**Comment by cesalazar** [comment]
Added on b13eef01ea952c177b7721ba010d6e8360e6ccdc
