### ISSUE TITLE
LedgerZ.org workshop: Plasma Fraud Proof Challenge with Cryptokitties rewards

### ISSUE THREAD

**Issue by oz1127** [cesalazar/berlinblockchainweek#53]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Plasma Fraud Proof Challenge (with Cryptokitties rewards)

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: In this workshop we will work with Johann Barbie on Plasma by example, for scaling and merkle-proofing DApps. True challengers will gain Cryptokitties!

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: LedgerZ.org workshop: Plasma Fraud Proof Challenge with Cryptokitties rewards

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
   In this workshop we will work with Johann Barbie on Plasma by example, for scaling and merkle- 
   proofing DApps. True challengers will gain Cryptokitties!
  -
    Agenda:
    1. Intro to Plasma, Classic vs Cash
    2. Merkle-trees and merkle-proofs
    3. Interactive session to create and submit proofs.
    4. Payout of crpyto-asset prices to fastest proofs
 -
    Notes:
    You will want to bring your laptop, blockchain knowledge and dev-skills
    Foods and drinks will be offered for participants
 -
    About the moderator: Johann is the Lead Link of the Research Circle at Parsec Labs, where he 
    focuses on Plasma research. His research aims at enabling smart contract execution on Plasma 
    chains.
    Twitter @johba @Parsec_Labs
    parseclabs.org
 -
# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-05
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-05

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '17:30'
# Time when the event ends. Can be left empty.
endTime: '19:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/ledgerz/events/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: TBD

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: TBA

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: workshop

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Johann Barbie

    # Can be left empty.
    title: Lead Link of the Research Circle at Parsec Labs

    # Can be left empty.
    company: ParsecLabs

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://parseclabs.org

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: 

    # The full URL, including http(s)://. Can be left empty.
    website: http://www.ledgerz.org

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    # bio: Here goes Carlos' description. Amet corporis laudantium obcaecati
    #  perferendis reiciendis rem perferendis. Magni qui reiciendis explicabo.
  -
    name: Johann Barbie
    title: Lead Link of the Research Circle at Parsec Labs
    company: ParsecLabs
    companyURL: https://parseclabs.org/
    twitter: @johba
    website: https://parseclabs.org
    bio:  Johann is the Lead Link of the Research Circle at Parsec Labs, where he 
    focuses on Plasma research. His research aims at enabling smart contract execution on Plasma 
    chains.
    # known as a co-founder of Ethereum and as a co-founder of Bitcoin Magazine.
  -
    # name: Kathleen Breitman
    # title: CEO
    # company: Tezos
    # companyURL: https://tezos.com/
    # twitter: breitwoman
    # website: http://kathleenbreitman.com
    # bio: Co-founder at Tezos, a fresh implementation of a blockchain which can
    #  amend its protocol.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
The address doesn't resolve on Google Maps. Could you please check it? otherwise it can't be included.
