### ISSUE TITLE
RCon3 should not be listed as a free event

### ISSUE THREAD

**Issue by kitblake** [cesalazar/berlinblockchainweek#68]
On the page https://blockchainweek.berlin/events/rchain-devcon3/ under "More information" the Cost of RCon3 is listed as free. This is not the case:
- General Admission is $700.00
- Studentl Admission is $50.00

**Comment by zulfacar** [comment]
@kitblake: Right but the got a voucher take BLOCKCHAINWEEK and then it is 10 € instead of 700, even cheaper for students like that
