### ISSUE TITLE
WIB Berlin Meetup 

### ISSUE THREAD

**Issue by SchmittLea** [cesalazar/berlinblockchainweek#92]
---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: 'WIB Berlin: Cryptoeconomics'

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: This is a talk about blockchain. This field is indexed by search
  engines and used to show a description on /events.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: 'WIB Berlin: Cryptoeconomics'

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis: Why should we care about crypto economics and token design? Crypto economics is a field that is relatively new to the world but rapidly evolving. The way we interact with each other and exchange value is moving towards decentralization. This means that we are creating a system where anything of value can be exchanged peer to peer without a central entity that determines and enforces rule sets or laws. Instead of placing trust in central custodians we rely on certain rules translated into code.

  -
    The way we design these protocols influences how we interact with each other in this system and what we deem valuable. Therefore, when designing these protocols it is essential to consider how they will be used, misused, who the different stakeholders are and what an adequate incentivisation mechanism looks like.
  -
    In this session we will explore how these systems evolve and what aspects are important to take into account when doing so.
  -
    'About WIB: By connecting across interests and backgrounds with a focus on females otherwise underrepresented in the blockchain world, we are working towards equality needed to build products, communities and economies that work for all. Everyone is invited to the meet-ups!'

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-11
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-11

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to acquire the tickets. Can be left empty.
tickets: pending

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Full Node

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Skalitzer Strasse 85-86, 10997 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    name: Simona Pop
    title: Community and Markteing
    company: the Bounty Network
    companyURL: https://bounties.network/
    twitter: 
    website: 
    bio: 
  -
    name: Anami Nguyen 
    title: Analyst
    company: J.P. Morgan 
    companyURL: 
    twitter: 
    website: https://medium.com/@anaminguyen
    bio: 
  -
    name: Cassidy Daly 
    title: Co-Founder
    company: Chlu 
    companyURL: https://chlu.io/
    twitter: 
    website: https://medium.com/@cassidy.daly
    bio: 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by cesalazar** [comment]
Thank you for submitting this event. Unfortunately the format is incorrect:
  - some necessary fields are commented (any line starting with a `#` symbol), and _will_ be ignored by the system.
  - the indentation is crucial, is not possible to randomly indent lines because the system won't be able to read them.

Please edit your issue using the [issue template](https://github.com/cesalazar/berlinblockchainweek/blob/master/.github/ISSUE_TEMPLATE) as a reference.

P.S. you can copy the original content of the template by clicking the `Raw` button on the link provided above.
